[build]
  publish = "."

[[redirects]]
  from = "/plans"
  to = "/plans.html"
  status = 200

[[redirects]]
  from = "/intake"
  to = "/intake.html"
  status = 200

[[redirects]]
  from = "/home"
  to = "/index.html"
  status = 200
